/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utdvvcc.presentacion;

import com.utdvvcc.conexion.ConexionBD;
import com.utdvvvcc.entidades.ManejoImagen;
import com.utdvvvcc.entidades.imagen;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jarteaga
 */
public class JIFConsultarTE extends javax.swing.JInternalFrame {

   
    private int id_usuario=MDIPrincipal.getvSeccion();
    
    private String placa="";
    private String marca="";
    private String modelo="";
    private String color="";
    private String categoria="";
    private int id;

    private boolean estadofoto;
    private boolean estadodata;
    
    private ConexionBD conexion;
    
    public JIFConsultarTE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        FOTO = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lb_placa = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_cat = new javax.swing.JLabel();
        lb_marca = new javax.swing.JLabel();
        lb_modelo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_color = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lb_estado = new javax.swing.JLabel();
        lb_permitir = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consultar TE -Tarifa Diferencial V 1.0- UTDVVCC");
        setPreferredSize(new java.awt.Dimension(850, 650));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CONSULTAR PLACA"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("PLACA");

        txt_placa.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        txt_placa.setToolTipText("Pulsar Enter para una busque más rapida.");
        txt_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_placaKeyPressed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/utdvvcc/recursos/buscar.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.setToolTipText("Buscar Placa");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_placa)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_placa))
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA VEHICULO"));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FOTO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FOTO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FOTO.setText("FOTO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FOTO, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FOTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_placa.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lb_placa.setForeground(new java.awt.Color(153, 0, 0));
        lb_placa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("CATEGORIA:");

        lb_cat.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lb_cat.setForeground(new java.awt.Color(153, 0, 0));
        lb_cat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_marca.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lb_marca.setForeground(new java.awt.Color(153, 0, 0));
        lb_marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_modelo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lb_modelo.setForeground(new java.awt.Color(153, 0, 0));
        lb_modelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("PLACA :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("LINEA:");

        lb_color.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lb_color.setForeground(new java.awt.Color(153, 0, 0));
        lb_color.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("MARCA: ");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("COLOR:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(lb_placa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_placa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_modelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_cat)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_estado.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lb_estado.setForeground(new java.awt.Color(153, 153, 0));
        lb_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_estado.setText("ACTIVO");

        lb_permitir.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lb_permitir.setForeground(new java.awt.Color(153, 153, 0));
        lb_permitir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_permitir.setText("PERMITIR PASO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_permitir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lb_estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_permitir)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
      consultar();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_placaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            consultar();
        }
    }//GEN-LAST:event_txt_placaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FOTO;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_cat;
    private javax.swing.JLabel lb_color;
    private javax.swing.JLabel lb_estado;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_modelo;
    private javax.swing.JLabel lb_permitir;
    private javax.swing.JLabel lb_placa;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables

        public void consultar()
        {
              try
        {
            conexion=new ConexionBD();
            ManejoImagen imagen=new ManejoImagen();
            imagen img=new imagen();
            
            String estadotxt="ACTIVO";
            String pasotxt="PERMITIR PASO";
            
            placa=txt_placa.getText().toUpperCase();
            
                    
            
            ResultSet rs = conexion.executeQuery("SELECT id_tarjetas_especiales,placa,estado,foto,data_complet FROM tb_tarjetas_especiales WHERE placa='"+placa+"' AND estado=true");
            
            if(rs.next()==true)
            {
                estadodata=rs.getBoolean("data_complet");
                estadofoto=rs.getBoolean("foto");
                id=rs.getInt("id_tarjetas_especiales");
                placa=rs.getString("placa");
                estadotxt="ACTIVO";
                pasotxt="DEJAR PASAR";
                lb_placa.setText(placa);
                lb_estado.setText(estadotxt);
                lb_permitir.setText(pasotxt);
                 lb_marca.setText("");
                 lb_modelo.setText("");
                 lb_color.setText("");
                 lb_cat.setText("");
                 txt_placa.setText("");
                 
                 conexion.executeUpdateQuery("INSERT INTO tb_pasadas_validas(placa,id_usuario)VALUES('"+placa+"', "+id_usuario+")");
                
                if(estadodata==true)
                {
                    ResultSet rs_=conexion.executeQuery("SELECT m.nombre_marca,l.descripcion,d.color,c.categoria FROM tb_tarjetas_especiales t JOIN tb_data_vehiculo d ON d.id_tarjetas_especiales=t.id_tarjetas_especiales "
                            + " JOIN tb_categoria c ON c.id_categoria=d.id_categoria JOIN tb_linea_marca l ON l.id_linea_marca=d.id_linea_marca JOIN tb_marca m ON m.id_marca=l.id_marca WHERE t.placa='"+placa+"' ");
                
                    if(rs_.next()==true)
                    {
                        lb_marca.setText(rs_.getString("nombre_marca"));
                        lb_modelo.setText(rs_.getString("descripcion"));
                        lb_color.setText(rs_.getString("color"));
                        lb_cat.setText(rs_.getString("categoria"));
                        
                    }
                    conexion.desconectar();
                }
                if(estadofoto==true)
                {
                    ResultSet rs_1=conexion.executeQuery("SELECT id_foto,id,nombre,foto_archivo,id_te FROM tb_foto_vehiculos WHERE id_te="+id+"");
                    
                    if(rs_1.next()==true)
                    {
                        img.setArchivo(imagen.ConvertirImagen(rs_1.getBytes("foto_archivo")));
                        double alto = img.getArchivo().getHeight(null) / Math.ceil(img.getArchivo().getHeight(null)/280f) ;
                        double ancho =img.getArchivo().getWidth(null) / Math.ceil(img.getArchivo().getWidth(null)/268f) ;
                        Icon icon = new ImageIcon( img.getArchivo().getScaledInstance((int)ancho,(int)alto, Image.SCALE_AREA_AVERAGING) );            
                        FOTO.setText("");
                        FOTO.setIcon( icon  );//coloca imagen en el JLabel
                    }
                }
                 conexion.desconectar();          
            }else
            {
                estadotxt="NO ACTIVO";
                pasotxt="PAGAR TARIFA PLENA";
                JOptionPane.showMessageDialog(null, "LA PLACA N° " + placa + " \n NO SE ENCUENTRA EN EL LISTADO Y/O NO ESTA ACTIVA", "Alerta", JOptionPane.WARNING_MESSAGE);
                lb_estado.setText(estadotxt);
                lb_permitir.setText(pasotxt);
                txt_placa.setText("");
                lb_marca.setText("");
                 lb_modelo.setText("");
                 lb_color.setText("");
                 lb_cat.setText("");
                 lb_placa.setText("");
                 FOTO.setText("");
                 //this.FOTO.setText("NO FOTO");
                 conexion.desconectar();
                
            
            }
            
         
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            conexion.desconectar();
        }
        }

}
