/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utdvvcc.presentacion;

import com.utdvvcc.conexion.ConexionBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jarteaga
 */
public class JIFSubirPlacas extends javax.swing.JInternalFrame {


  private final ConexionBD conexion =new ConexionBD();;
  private int idusuario;
  DropXLS drop;
   
    
    public JIFSubirPlacas() {
        initComponents();
       
        
       JOptionPane.showMessageDialog(null, "NOTA: - UTILIZAR SOLO FORMATO XLS\n-VERIFICAR QUE EL ARCHIVO TENGA SOLO DOS COLUMNAS, 'FORM Y PLACAS'. ", "Alerta", JOptionPane.WARNING_MESSAGE);
        
        //drop=new DropXLS(tb_placas);
       
      
        
        drop=new DropXLS(tb_placas);
       /// tb_placas.setModel(modelo);
        
  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_placas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_subir = new javax.swing.JButton();
        p_encabezado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Subir Placas  -Tarifa Diferencial V 1.0- UTDVVCC");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Archivo XLS en la Tabla"));

        tb_placas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "FORM", "PLACAS"
            }
        ));
        tb_placas.setToolTipText("Soltar archivo de excel Formato XLS");
        jScrollPane1.setViewportView(tb_placas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar Placas Base de datos"));

        btn_subir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/utdvvcc/recursos/bd.png"))); // NOI18N
        btn_subir.setToolTipText("Subir Placas a la Base de datos");
        btn_subir.setContentAreaFilled(false);
        btn_subir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_subir.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btn_subir)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_subir)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("CARGAR PLACAS A LA BASE DE DATOS");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/utdvvcc/recursos/desc.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(117, 117, 117))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirActionPerformed
        try
            
        {
            
          int opc=JOptionPane.showConfirmDialog(null,"Desea subir las placas a la base de datos?", "Aviso!", JOptionPane.YES_NO_OPTION); 

              if(opc==JOptionPane.YES_OPTION)
              
              {
    
           if(tb_placas.getRowCount()== 0 && tb_placas.getSelectedRow()==-1)
        {
         
           throw new Exception("La Tabla no tiene ningún item adicionado!");

        } 
                  
                  
            String form="", placa="";
            
            
            
           
            idusuario=MDIPrincipal.getvSeccion();
            
              for(int i=0;i<tb_placas.getRowCount();i++)
              {
                  form=(String)tb_placas.getValueAt(i,0);
                  placa=(String)tb_placas.getValueAt(i,1);
                  
                  if(form.equals("") || placa.equals(""))
                  {
                    throw new Exception("La columna Form y/o Placa estan vacias");

                  }
                  
                  conexion.executeUpdateQuery("INSERT INTO tb_tarjetas_especiales (placa, id_usuario,form)VALUES('"+placa+"',"+idusuario+", '"+form+"')");
                  conexion.desconectar();
              }
              JOptionPane.showMessageDialog(null,"Se registraron un total de: " + tb_placas.getRowCount()+ " Placas");
              
              //conexion.desconectar();
              
           }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_subirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_subir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_encabezado;
    private javax.swing.JTable tb_placas;
    // End of variables declaration//GEN-END:variables
}
